language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
matrix:
  allow_failures:
  - julia: nightly
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("RobustAdaptiveMetropolisSampler")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - os: windows
      arch: x86
      julia: 1.0
      name: "Julia: 1.0 (32bit)"
    - os: windows
      arch: x86
      julia: 1.1
      name: "Julia: 1.1 (32bit)"
    - os: windows
      arch: x86
      julia: 1.2
      name: "Julia: 1.2 (32bit)"
    - os: windows
      arch: x86
      julia: nightly
      name: "Julia: nightly (32bit)"
